### ISSUE TITLE
Metadata refresh hangs or tries to reset unmodifiable collection.

### ISSUE THREAD

**Issue by alltomsport** [spring-projects/spring-security-saml#153]
Hi!
Firstly, thanks for a great library!
We are using it in order to communicate via SAML with a IDP. Unfortunately we have the problem that the metadata refresh seems to lock up, the cure so far has been to restart our application server. This is clearly the same problem reported in this issue: 
https://github.com/spring-projects/spring-security-saml/commit/4eae6c733af65fbefdae1a45dc2d54310617593a

But when i try out the latest build (2016-03-10, with the fix) a get another error.

`java.lang.UnsupportedOperationException: null
    at java.util.Collections$UnmodifiableCollection.clear(Collections.java:1074)
    at org.opensaml.saml2.metadata.provider.ChainingMetadataProvider.setProviders(ChainingMetadataProvider.java:104)
    at org.springframework.security.saml.metadata.MetadataManager.refreshMetadata(MetadataManager.java:225)
    at org.springframework.security.saml.metadata.CachingMetadataManager.refreshMetadata(CachingMetadataManager.java:86)
    at org.springframework.security.saml.metadata.MetadataManager$RefreshTask.run(MetadataManager.java:1040)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
`

MetadataManager.refreshMetadata() is called by the RefreshTask.
refreshMetadata() tries to:

`super.setProviders(Collections.<MetadataProvider>emptyList());`

but the provider list is already initialized as an unmodifiable list.

So my question, will this be fixed and is there going to be a new stable release any soon, perhaps in May?

My workaround now is to use the 1.0.1.RELEASE with the refresh timer task deactivated.

**Comment by richardbarabe** [comment]
I get this stack after booting my app and going to /saml/metadata and I get a white page (obviously).
I use spring-saml 1.0.2.RELEASE and I see opensaml version 2.6.1 in the class path.
Is this release broken of could it be due to a configuration problem on my side ?

I really dont get this one.

**Comment by richardbarabe** [comment]
Nevermind.  This was due to a bad migration of the configuration from a previous version.
I corrected the config based on the sample, and it now works.

**Comment by jzheaux** [comment]
Fixed via 8c0aaf90ef245e4147e59918b362478072549f24
