### ISSUE TITLE
Cannot use a metadataFilter except MetadataFilterChain (UnsupportedOperationException)

### ISSUE THREAD

**Issue by daviddascalescu** [spring-projects/spring-security-saml#160]
Defining a Metadata Filter, other than org.opensaml.saml2.metadata.provider.MetadataFilterChain to be used fails with UnsupportedOperationException upon application initialization:
```
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148) ~[?:1.8.0_45]
	at java.util.AbstractList.add(AbstractList.java:108) ~[?:1.8.0_45]
	at org.springframework.security.saml.metadata.MetadataManager.initializeProviderFilters(MetadataManager.java:525) 
...
```
This happens because the code in org.springframework.security.saml.metadata.MetadataManager assumes that the filters list from opensaml always allows addition:
```
if (currentFilter instanceof MetadataFilterChain) {
    log.debug("Adding signature filter into existing chain");
    MetadataFilterChain chain = (MetadataFilterChain) currentFilter;
    chain.getFilters().add(filter);
} else {
    log.debug("Combining signature filter with the existing in a new chain");
    MetadataFilterChain chain = new MetadataFilterChain();
    chain.getFilters().add(currentFilter);
    chain.getFilters().add(filter);
}
```
but this is not true on the else branch with a freshly created MetadataFilterChain. Even if allowed initially in opensaml the implementation of org.opensaml.saml2.metadata.provider.MetadataFilterChain is no longer initializing the filter list with an ArrayList, but rather with Collections.emptyList();

The workaround is to always use a wrapper MetadataFilterChain, and that's fine, however discovering the workaround takes a lot of time and fixing this hopefully saves other's time.

We detected this by trying to filter out Metada for SPs from, let's say InCommon, so we defined at top level an "idpOnly" bean as below:
```
<bean id="idpOnly" class="org.opensaml.saml2.metadata.provider.EntityRoleFilter">
	<constructor-arg>
  	<list value-type="javax.xml.namespace.QName">
  		<bean class="javax.xml.namespace.QName">
				 <constructor-arg value="urn:oasis:names:tc:SAML:2.0:metadata"/>
				 <constructor-arg value="IDPSSODescriptor"/>
  		</bean>
  	</list>
  </constructor-arg>
</bean>
```
and then referenced it in the "metadata" bean as below:
```
<bean class="org.springframework.security.saml.metadata.ExtendedMetadataDelegate">
	<constructor-arg>
	  <bean
	      class="org.opensaml.saml2.metadata.provider.ResourceBackedMetadataProvider">
	      <constructor-arg>
	          <bean class="java.util.Timer"/>
	      </constructor-arg>
	      <constructor-arg>
	          <bean class="org.opensaml.util.resource.HttpResource">
	              <constructor-arg value="http://md.incommon.org/InCommon/InCommon-metadata.xml"/>
	          </bean>
	      </constructor-arg>
	      <property name="parserPool" ref="parserPool"/>
	      <property name="metadataFilter" ref="idpOnly"/>                   
	  </bean>
	</constructor-arg>
	 <property name="metadataTrustCheck" value="false"/>
</bean>
```
Thank you and kind regards

**Comment by daviddascalescu** [comment]
As an extra note even if chain.getFilters().add(currentFilter) worked on the else branch:
```
MetadataFilterChain chain = new MetadataFilterChain();
    chain.getFilters().add(currentFilter);
    chain.getFilters().add(filter);
```  
in the end the newly created chain object would remain unconnected to the provider. A provider.setMetadataFilter(chain) would be necessary.

Also, I think I have discovered another issue in this area, in case we use <property name="metadataTrustCheck" value="true"/> in the bean settings for the ExtendedMetada (actually the default is true) and we have a signed EntitiesDescriptor as in case of a Federation such as InCommon (http://md.incommon.org/InCommon/InCommon-metadata.xml) then, if a filter is involved in the provider and it eliminates some metadata, the EntitiesDescriptor is always valid with regard to the signature (although the cert was not added to the truststore) - so it seems no validation is actually performed. I think the signature filter should not be added at the end of the list in MetadataManager.initializeProviderFilters(...), but rather at the beginning as elements are removed from the EntitiesDescriptor and probably opensaml removes the signature, too, as it wouldn't make sense to stay. Hence it is better to have the signature validation filter perform first. Should I report a separate issue?

Thank you

**Comment by joni-nousiainen** [comment]
I also hit both of the above-mentioned problems yesterday. Just like @daviddascalescu I wanted to filter everything except IdPs from remote metadata but also do metadata signature check before that.

Here is a workaround that worked for me:

```java
@Bean
public CachingMetadataManager metadataManager() throws MetadataProviderException {
  return new CachingMetadataManager(Arrays.asList(
    idpMetadataProvider()
  )) {
    @Override
    protected void initializeProviderFilters(ExtendedMetadataDelegate provider) throws MetadataProviderException {
      super.initializeProviderFilters(provider);
      MetadataFilter filter = provider.getMetadataFilter();
      if (filter instanceof MetadataFilterChain) {
        MetadataFilterChain filterChain = (MetadataFilterChain) filter;
        moveSignatureValidationFilterFirst(filterChain.getFilters());
      }
    }

    private void moveSignatureValidationFilterFirst(List<MetadataFilter> filters) {
      // ...
    }
  };
}
```

**Comment by OrangeDog** [comment]
I think the filter-before-validate problem could also be solved by allowing filters on the `MetadataManager`.
However, you currently get:
> java.lang.UnsupportedOperationException: Metadata filters are not supported on ChainingMetadataProviders

@daviddascalescu
FYI you don't need to construct the QName - there's the field `IDPSSODescriptor.DEFAULT_ELEMENT_NAME`.
