### ISSUE TITLE
SSO using HTTP-Artifact binding

### ISSUE THREAD

**Issue by blop** [spring-projects/spring-security-saml#202]
Hello,

It seems there is no way to achieve SSO using a HTTP-Artifact binding.

As it's looking for a "artifact resolution service endpoint", which is not provided when using the MetadataGenerator.
I don't see any endpoint servlet/filters neither for artifact resolution.

Or am I missing something?

**Comment by vschafer** [comment]
HTTP-Artifact for SSO is supported. Search for artifact in http://docs.spring.io/spring-security-saml/docs/current/reference/htmlsingle/

<bean class="org.springframework.security.saml.metadata.MetadataGenerator">
	<property name="bindingsSSO"><list><value>artifact</value></list></property>
</bean>

**Comment by blop** [comment]
Yes, I'm not overriding the bindingsSSO property so I'm using the default value which is : 
`
    private Collection<String> bindingsSSO = Arrays.asList("post", "artifact");
`

When displaying the SP metadata, I do get an artifact related information, like : 
`
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://vdab.ozone.cloud/saml/SSO" index="0" isDefault="true"/>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact" Location="https://vdab.ozone.cloud/saml/SSO" index="1"/>
`
But there is no **ArtifactResolutionService** declared in it.
I don't see how to configure it.

Then when I'm trying SSO, it's trying to encode the message as an artifact, it's going into org.opensaml.saml2.binding.artifact.SAML2ArtifactType0004Builder.getAcsEndpoint() which is looking for a ArtifactResolutionService endpoint, which does not exists.

Maybe I need to create that ArtifactResolutionService endpoint somewhere?

**Comment by vschafer** [comment]
ArtifactResolutionService would only be needed in case of SP sending out a SAML Request using Artifact binding, instead of receiving a Response. Spring SAML supports sending of Request using HTTP-Redirect or HTTP-POST (as Requests are very small, there's no need for HTTP-Artifact support), and receiving of Response using HTTP-POST or HTTP-Artifact.

I suspect you might be setting your WebSSOProfileOptions with binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact", which would be instructing Spring SAML to send out the Request using HTTP-Artifact. While what you likely want is to use HTTP-Artifact to receive Response instead. In order to do so, set property assertionConsumerIndex to index of WebSSO enpoint with HTTP-Artifact binding in the IDP's metadata.

**Comment by blop** [comment]
Yes exactly.
Actually, I had to force the use of HTTP-POST in my WebSSOProfileOptions.

Otherwise org.springframework.security.saml.websso.WebSSOProfileImpl#getSingleSignOnService() is selecting the first SingleSignOnService found in the XML, which happen to be the HTTP-Artifact in my case.

If HTTP-Artifact is not supported for sending of requests, maybe WebSSOProfileImpl should ignore it automatically somehow and select the next one.

**Comment by vschafer** [comment]
Can you please attach your Spring SAML config file which leads the system to call org.opensaml.saml2.binding.artifact.SAML2ArtifactType0004Builder.getAcsEndpoint() ? I'll have a look at how can that actually happen - it shouldn't..

**Comment by blop** [comment]
It's part a a big configuration, not sure I can share it.

Here is the first stack (when calling /saml/login) : 
```
Caused by: org.opensaml.ws.message.encoder.MessageEncodingException: Unable to builder artifact for message to relying party
	at org.opensaml.saml2.binding.encoding.HTTPArtifactEncoder.buildArtifact(HTTPArtifactEncoder.java:232)
	at org.opensaml.saml2.binding.encoding.HTTPArtifactEncoder.getEncode(HTTPArtifactEncoder.java:195)
	at org.opensaml.saml2.binding.encoding.HTTPArtifactEncoder.doEncode(HTTPArtifactEncoder.java:137)
	at org.opensaml.ws.message.encoder.BaseMessageEncoder.encode(BaseMessageEncoder.java:52)
	at org.springframework.security.saml.processor.SAMLProcessorImpl.sendMessage(SAMLProcessorImpl.java:224)
	at org.springframework.security.saml.processor.SAMLProcessorImpl.sendMessage(SAMLProcessorImpl.java:192)
	at org.springframework.security.saml.websso.AbstractProfileBase.sendMessage(AbstractProfileBase.java:148)
	at org.springframework.security.saml.websso.WebSSOProfileImpl.sendAuthenticationRequest(WebSSOProfileImpl.java:105)
	at org.springframework.security.saml.SAMLEntryPoint.initializeSSO(SAMLEntryPoint.java:226)
	at org.springframework.security.saml.SAMLEntryPoint.commence(SAMLEntryPoint.java:153)
	... 59 common frames omitted
```

It's selecting the HTTPArtifactEncoder, because the Endpoint (org.opensaml.saml2.metadata.impl.SingleSignOnServiceImpl) has bindingId = urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact.

This is the SingleSignOnService selected by org.springframework.security.saml.websso.WebSSOProfileImpl#getSingleSignOnService(), which is apparently selecting the first <SingleSignOnService> entry in the <IDPSSODescriptor> .

**Comment by vschafer** [comment]
Got it, the bug is in WebSSOProfileImpl:

```
    /**
     * Determines whether given SingleSignOn service can be used together with this profile. Bindings POST, Artifact
     * and Redirect are supported for WebSSO.
     *
     * @param endpoint endpoint
     * @return true if endpoint is supported
     * @throws MetadataProviderException in case system can't verify whether endpoint is supported or not
     */
    protected boolean isEndpointSupported(SingleSignOnService endpoint) throws MetadataProviderException {
        return org.opensaml.common.xml.SAMLConstants.SAML2_POST_BINDING_URI.equals(endpoint.getBinding()) ||
                org.opensaml.common.xml.SAMLConstants.SAML2_ARTIFACT_BINDING_URI.equals(endpoint.getBinding()) ||
                org.opensaml.common.xml.SAMLConstants.SAML2_REDIRECT_BINDING_URI.equals(endpoint.getBinding());
```

The code should not be allowing HTTP-Artifact here. Thank you for reporting it! It's a rare case, as IDPs typically don't declare SingleSignOnService with Artifact binding.

I'll push a fix when I have a moment. As a workaround you should be able to circumvent this by simply changing the order of the SingleSignOnServices in your IDP metadata, so that HTTP-Redirect or HTTP-POST is declared first. Or just take out the SingleSignOnService with HTTP-Artifact binding.

**Comment by blop** [comment]
Great.
Thank you ;-)

**Comment by hgoetzger** [comment]
Thanks for tracking this down.

Right now I have exact this effect by using SAP-Portal as IDP using spring.security.saml2.version 1.0.2.RELEASE in the SP.

We now use a unsigned MD and change the order of the SSO-Bindungs having HTTP-POST before  HTTP-Artifact.
