### ISSUE TITLE
NoClassDefFoundError with Spring 5

### ISSUE THREAD

**Issue by tmurakam** [spring-projects/spring-security-saml#211]
With Spring framework 5.0.0, SAMLBootstrap class throws NoClassDefFoundError.

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.saml.SAMLBootstrap]: No default constructor found; nested exception is java.lang.NoClassDefFoundError: org/springframework/beans/factory/access/BootstrapException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:84)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1223)
	... 59 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/beans/factory/access/BootstrapException
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:79)
	... 60 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.beans.factory.access.BootstrapException
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1285)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
	... 65 common frames omitted
```

The BootstrapException class seems to be removed in Spring 5.

**Comment by kajh** [comment]
Thanks for creating a PR with a fix! Any hope of getting it merged and released soon? We would love to upgrade to Spring 5, but this is a blocker.

**Comment by Raiyuu** [comment]
Hello! I'm in similar situation as kajh. This issue is blocking us from upgrade to Spring 5. Is there any time prediction for release that contains this fix? 
Thank you!

**Comment by brankoiliccc** [comment]
Any news on this ?

**Comment by jackmatt2** [comment]
I need this too.

**Comment by mle-enso** [comment]
+1

**Comment by sw-samuraj** [comment]
For me, it's a blocking issue for _Spring 5_ upgrade too.

There is a version `1.0.3.BUILD-SNAPSHOT` on the [project site](https://projects.spring.io/spring-security-saml/), but it's nowhere in the repositories (snapshot/milestone).

Is there any date, or roadmap available?

**Comment by olasundell** [comment]
+1. We're about to write a new piece of software using Spring 5, but this is the only blocker at the moment. :(

**Comment by rwinch** [comment]
@sw-samuraj @olasundell Thanks for the feedback. You should be able to find it in the SNAPSHOT repository now https://repo.spring.io/snapshot/org/springframework/security/extensions/spring-security-saml2-core/1.0.2.BUILD-SNAPSHOT/ Can you please give it a try? If it works with Spring Framework 5 for you, we can go ahead and schedule a release.

Thanks!

**Comment by sw-samuraj** [comment]
@rwinch Works well for me, no exception during deployment/startup.

I'm using following _Gradle_ set up:

```groovy
repositories {
    maven { url 'https://repo.spring.io/snapshot' }
}
dependencies {
    compile 'org.springframework.security.extensions:spring-security-saml2-core:1.0.2.BUILD-SNAPSHOT'
}
```

**Comment by olasundell** [comment]
Works for me as well @rwinch - sorry for the late feedback, other stuff came in between.

**Comment by waded** [comment]
https://repo.spring.io/snapshot/org/springframework/security/extensions/spring-security-saml2-core/1.0.2.BUILD-SNAPSHOT/ is working for us with Spring 5.0.2. We're no longer seeing SAMLBootstrap. Would like to see a release with this fix.

**Comment by rwinch** [comment]
This is now released in 1.0.3.RELEASE http://repo1.maven.org/maven2/org/springframework/security/extensions/spring-security-saml2-core/1.0.3.RELEASE/

PS: We had a build issue where the build was reverted to 1.0.2.BUILD-SNAPSHOT where as it should have been 1.0.3.BUILD-SNAPSHOT. No harm done since it was a SNAPSHOT though.

**Comment by sw-samuraj** [comment]
I checked my two applications with the new release version `1.0.3.RELEASE` and it works fine.

Thank you @rwinch !

**Comment by rwinch** [comment]
Thanks for confirming the fix in the release @sw-samuraj Thank you to everyone who contributed to this issue and the PR!

**Comment by aroneous** [comment]
A word of warning to anybody who might be encountering an "it works on my machine!" situation here: I have, on two different machines, two copies of what is nominally version 1.0.2.RELEASE that are not identical. One version has the fix for the issue in it; one does not.

Also, the [version of the relevant file tagged with 1.0.2.RELEASE](https://github.com/spring-projects/spring-security-saml/blob/1.0.2.RELEASE/core/src/main/java/org/springframework/security/saml/SAMLBootstrap.java) has the fix in it.

Of course the proper solution is to upgrade to a version that definitively has the fix, but this led to a fun game of "why is this failing in the QA environment but not for me??"
