### ISSUE TITLE
LogoutResponse not getting sent due to MetadataProviderException

### ISSUE THREAD

**Issue by dtreskunov** [spring-projects/spring-security-saml#316]
When using IdP initiated logout, the logout response is not getting sent back to the IdP.

In the `sendLogoutResponse` method of `SingleLogoutProfileImpl.java`, the peer entity ID is getting set to `null` if the `ID` attribute of `IDPSSODescriptor` is not set. I believe that line 246 (see excerpt below) is not necessary.

```
2018-09-14 12:23:58.699 -0700 (,,,,) catalina-exec-6 : INFO  org.springframework.security.saml.log.SAMLDefaultLogger - LogoutRequest;FAILURE;127.0.0.1;XXX;;;;org.opensaml.saml2.metadata.provider.MetadataProviderException: IDP with name null wasn't found in the list of configured IDPs
	at org.springframework.security.saml.util.SAMLUtil.getIDPDescriptor(SAMLUtil.java:370)
	at org.springframework.security.saml.websso.SingleLogoutProfileImpl.sendLogoutResponse(SingleLogoutProfileImpl.java:219)
```

Excerpt from [SingleLogoutProfileImpl.java](https://github.com/spring-projects/spring-security-saml/blob/1.0.4.RELEASE/core/src/main/java/org/springframework/security/saml/websso/SingleLogoutProfileImpl.java#L246) (1.0.4.RELEASE):

```
    public void sendLogoutResponse(SAMLMessageContext context, String statusCode, String statusMessage) throws MetadataProviderException, SAMLException, MessageEncodingException {
        //...
        IDPSSODescriptor idpDescriptor = SAMLUtil.getIDPDescriptor(metadata, context.getPeerEntityId());
        //...
        // the following will overwrite the peer entity ID with null - should be safe to remove
        context.setPeerEntityId(idpDescriptor.getID());
        //...
        sendMessage(context, signMessage);
    }
```

**Comment by fhanik** [comment]
This was merged at https://github.com/spring-projects/spring-security-saml/pull/317
