### ISSUE TITLE
calling spring rest service via react problem

### ISSUE THREAD

**Issue by ali-esmaily** [spring-projects/spring-security-saml#354]
I have two applications:  react as frontend and spring boot as backend 

I utilized your spring boot sample to connect to an authentication server by SAML protocol.
when is call its services from browser's address bar it works correctly.
![image](https://user-images.githubusercontent.com/8143305/52161261-d7b07280-26d7-11e9-8d10-51e78cc46c0d.png)

But my problem is when Reactjs sent a request to spring boot app the spring returned SAML authentication XML as a response to the react instead of JSON that I expected. the following pictures.

![image](https://user-images.githubusercontent.com/8143305/52161279-0e868880-26d8-11e9-8f86-43f4464dee62.png)

![image](https://user-images.githubusercontent.com/8143305/52161272-f3b41400-26d7-11e9-8bc2-a7d838d9ff30.png)

bellow is my SAML configs.

    protected void configure(final HttpSecurity http) throws Exception {
        http.cors()
                .and()
                .authorizeRequests()
                .antMatchers("/saml*").permitAll()
                .anyRequest().authenticated()
                .and()
                .apply(saml())
                .serviceProvider()
                .keyStore()
                .storeFilePath(this.keyStoreFilePath)
                .password(this.password)
                .keyname(this.keyAlias)
                .keyPassword(this.password)
                .and()
                .protocol("https").entityId("pardazeshgaranSP")
                .hostname(String.format("%s:%s", "172.23.23.201", this.port))
                .basePath("/")
                .and()
                .identityProvider()
                .metadataFilePath(this.metadataUrl)
        .discoveryEnabled(false);
    }

`@Bean
public CorsConfigurationSource corsConfigurationSource() {
        final CorsConfiguration configuration = new CorsConfiguration();
        configuration.setAllowedOrigins(Collections.singletonList("*"));
        configuration.setAllowedMethods(Arrays.asList("HEAD",
                "GET", "POST", "PUT", "DELETE", "PATCH")); 
        configuration.setAllowCredentials(true);
        configuration.setAllowedHeaders(Arrays.asList("Authorization", "Cache-Control", "Content-Type"));
        final UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        source.registerCorsConfiguration("/**", configuration);
        return source;
    }`

and also i've seen this error in project logs

o.s.security.saml.log.SAMLDefaultLogger  : AuthNResponse;FAILURE;172.23.23.201;pardazeshgaranSP;10.8.8.176;pardazeshgaran;;org.opensaml.common.SAMLException: InResponseToField of the Response doesn't correspond to sent message a4i6198igj2ee6271i2g65735fa4iab
                at org.springframework.security.saml.websso.WebSSOProfileConsumerImpl.processAuthenticationResponse(WebSSOProfileConsumerImpl.java:139)
                at org.springframework.security.saml.SAMLAuthenticationProvider.authenticate(SAMLAuthenticationProvider.java:82)
                at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:174)
                at org.springframework.security.saml.SAMLProcessingFilter.attemptAuthentication(SAMLProcessingFilter.java:87)
                at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
                at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
                at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
                at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

**Comment by fhanik** [comment]
If your SP session changed, the SP rejects the incoming message because it can't find the outgoing message. 

https://github.com/spring-projects/spring-security-saml/blob/3769831d09cf3c66b0bc65416c3db85869c2e37c/docs/reference/docbook/troubleshooting.xml#L22

Per documentation. The work around is to not track messages IDs by using the `EmptyStorageFactory`.

**Comment by Brajendra** [comment]
@ali-esmaily Did you find the solution?
