### ISSUE TITLE
Error: Trying to clear an unmodifiable collection

### ISSUE THREAD

**Issue by nbosecker** [spring-projects/spring-security-saml#499]
Hi-
I have encountered the same bug described here: https://github.com/spring-projects/spring-security-saml/issues/153
We're using 1.0.3 RELEASE and saml 2.6.1. 
Comments on that previous error indicate there is some configuration change I can do to mitigate - but the actual fix is not described. Can anyone help?

Here is the error:
30-Sep-2020 16:46:05.319 SEVERE [catalina-exec-3] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [saml] in context with path [/sso] threw exception
	java.lang.UnsupportedOperationException
		at java.base/java.util.Collections$UnmodifiableCollection.clear(Collections.java:1079)
		at org.opensaml.saml2.metadata.provider.ChainingMetadataProvider.setProviders(ChainingMetadataProvider.java:104)
		at org.springframework.security.saml.metadata.MetadataManager.refreshMetadata(MetadataManager.java:225)
		at org.springframework.security.saml.metadata.CachingMetadataManager.refreshMetadata(CachingMetadataManager.java:86)
		at org.springframework.security.saml.metadata.MetadataGeneratorFilter.processMetadataInitialization(MetadataGeneratorFilter.java:137)
		at org.springframework.security.saml.metadata.MetadataGeneratorFilter.doFilter(MetadataGeneratorFilter.java:86)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
		at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
		at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1627)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by jzheaux** [comment]
@nbosecker I believe this is an issue with OpenSAML that is addressed in a later version. Have you tried using one of the more recent versions of `spring-security-saml`?
